# -*- coding: utf-8 -*-
"""radar_edit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JXvTfJ0XfKnEtYvG6BdH0e8DDnQy6xtw
"""

"""#**RADAR PLOT**

**Importing required libraries**
"""

import pandas as pd
import matplotlib.pyplot as plt
from soccerplots.radar_chart import Radar

"""**Reading in the data**"""

df = pd.read_csv('player_data.csv')

df.head()

"""**Sorting players names**"""

df['Player'] = df['Player'].str.split('\\', expand=True)[0]

"""**Player variable**"""

player1='Harry Kane'
player2='Mohamed Salah'

"""**Creating player dataframe**"""

df = df[(df['Player']== player1) | (df['Player']== player2)].reset_index()

"""**Creating squad dataframe**"""

df_squad = df.drop(['Gls','Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'Dist', 'xG', 'npxG', 'npxG/Sh', 'G-xG', 'np:G-xG'], axis = 1)
df_squad.reset_index()
df_squad.head()

df = df.drop(['index','Rk', 'Nation','Pos','Age', 'Squad', 'Born','90s','PK', 'FK', 'PKatt', 'Matches'], axis=1)

df.columns

"""**Squad variable**"""

squad1 = df_squad['Squad'][0]
squad1

squad2 = df_squad['Squad'][1]
squad2

"""**Get parameters**"""

params = list(df.columns)

params = params[1:]
params

"""**Add ranges to list of tuple pairs**"""

ranges = []
a_values = []
b_values = []

for x in params:
        a = min(df[params][x])
        a = a - (a * 0.25)
        b = max(df[params][x])
        b = b + (b * 0.25)

        ranges.append((a,b))

for x in range(len(df['Player'])):
    if df['Player'][x] == player1:
        a_values = df.iloc[x].values.tolist()
    if df['Player'][x] == player2:
        b_values = df.iloc[x].values.tolist()


a_values = a_values[1:]
b_values = b_values[1:]

values  = [a_values, b_values]

"""**Title**"""

title = dict(
    title_name =player1,
    title_color = 'red',
    subtitle_name = squad1,
    subtitle_color = 'red',
    title_name_2 =player2,
    title_color_2 = 'blue',
    subtitle_name_2 = squad2,
    subtitle_color_2 = 'blue',
    title_fontsize = 18,
    subtitle_fontsize = 15
)

"""**End note**"""

endnote = 'Deji Yekeen \ndata via FBREF /   Statsbomb'

"""**Radar**"""

radar = Radar()

"""**Radar plot**"""

fig, ax = radar.plot_radar(ranges=ranges, params=params,values=values,
                            radar_color=['red','blue'],
                            alphas=[.75, .6],
                                title=title,
                                endnote=endnote,
                                compare=True)